# Generated by Django 5.0.6 on 2024-06-21 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
